# Generated by Django 5.1.2 on 2025-08-07 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_mainuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('payment', models.CharField(default='unpaied', max_length=50)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.rider')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=20)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='users.driver')),
                ('rider', models.ManyToManyField(related_name='rides', through='rides.Reservation', to='users.rider')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.ride'),
        ),
    ]
