# Generated by Django 5.1.2 on 2025-08-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_reservation_payment_alter_reservation_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='time',
            new_name='arrival_time',
        ),
        migrations.AddField(
            model_name='ride',
            name='depature_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
