# Generated by Django 5.1.2 on 2025-08-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_rename_time_ride_arrival_time_ride_depature_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='depature_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
