# Generated by Django 5.1.2 on 2025-09-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_alter_ride_depature_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
