# Generated by Django 5.1.2 on 2025-09-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_ride_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='car_image',
        ),
    ]
