# Generated by Django 5.1.2 on 2025-09-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_remove_ride_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
