# Generated by Django 5.1.2 on 2025-09-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_ride_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='depature_time',
        ),
        migrations.AddField(
            model_name='ride',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
