# Generated by Django 5.1.2 on 2025-09-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_remove_ride_depature_time_ride_departure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='cost',
            field=models.CharField(max_length=50),
        ),
    ]
