# Generated by Django 5.1.2 on 2025-09-09 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_alter_ride_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='departure_time',
            new_name='depature_time',
        ),
    ]
