# Generated by Django 5.1.2 on 2025-09-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0010_rename_departure_time_ride_depature_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='depature_time',
            new_name='departure_time',
        ),
    ]
