# Generated by Django 6.0.2 on 2026-03-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0011_rename_depature_time_ride_departure_time'),
        ('users', '0016_alter_driver_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('ride', 'rider')},
        ),
    ]
