# Generated by Django 5.2.5 on 2026-05-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0015_ride_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
