# Generated by Django 5.2.5 on 2026-05-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0016_reservation_pickup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='pickup_location',
            field=models.CharField(default='qadmus', max_length=255),
            preserve_default=False,
        ),
    ]
