# Generated by Django 5.2.5 on 2026-05-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0017_alter_reservation_pickup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
