# Generated by Django 5.2.5 on 2026-06-08 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0018_alter_reservation_status'),
        ('users', '0021_driver_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='car_image',
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='users.driver'),
        ),
    ]
