# Generated by Django 5.2.5 on 2026-08-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0019_remove_ride_car_image_alter_ride_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='arrival_time',
        ),
        migrations.AddField(
            model_name='ride',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='expected_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
