# Generated by Django 5.2.5 on 2026-08-09 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0020_remove_ride_arrival_time_ride_departure_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rides.ride'),
        ),
    ]
