# Generated by Django 5.2.5 on 2026-07-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='payment_method',
            field=models.CharField(choices=[('syriatel_cash', 'Syriatel Cash'), ('mtn_cash', 'MTN Cash')], max_length=20),
        ),
    ]
