# Generated by Django 5.2.5 on 2026-07-02 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_depositrequest_payment_method'),
        ('rides', '0019_remove_ride_car_image_alter_ride_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='deposit_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.depositrequest'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.reservation'),
        ),
    ]
