# Generated by Django 5.2.5 on 2026-07-03 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_deposit_request_transaction_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='deposit_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.depositrequest'),
        ),
    ]
