# Generated by Django 5.2.5 on 2026-08-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_transaction_deposit_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='payment_method',
            field=models.CharField(choices=[('syriatel_cash', 'Syriatel Cash'), ('mtn_cash', 'MTN Cash'), ('sham_cash', 'Sham Cash')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('payment', 'Payment')], max_length=20),
        ),
    ]
