# Generated by Django 5.2.5 on 2026-08-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='payment_method',
            field=models.CharField(choices=[('syriatel_cash', 'Syriatel Cash'), ('sham_cash', 'Sham Cash')], max_length=20),
        ),
    ]
