# Generated by Django 5.2.5 on 2026-08-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_depositrequest_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('payment', 'Payment'), ('earning', 'Earning'), ('refund', 'Refund')], max_length=20),
        ),
    ]
