# Generated by Django 5.1.2 on 2025-08-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mainuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
