# Generated by Django 5.1.2 on 2025-08-14 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_reservation_payment_alter_reservation_status_and_more'),
        ('users', '0003_alter_mainuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='upcoming_trips',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='rides.ride'),
            preserve_default=False,
        ),
    ]
