# Generated by Django 5.1.2 on 2025-08-14 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_reservation_payment_alter_reservation_status_and_more'),
        ('users', '0004_driver_upcoming_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='past_trips',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='past_rides', to='rides.ride'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='upcoming_trips',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uncoming_rides', to='rides.ride'),
        ),
    ]
