# Generated by Django 5.1.2 on 2025-08-14 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_reservation_payment_alter_reservation_status_and_more'),
        ('users', '0005_driver_past_trips_alter_driver_upcoming_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='past_trips',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='rider_past_rides', to='rides.ride'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rider',
            name='upcoming_trips',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='rider_uncoming_rides', to='rides.ride'),
            preserve_default=False,
        ),
    ]
