# Generated by Django 5.1.2 on 2025-08-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rider_past_trips_rider_upcoming_trips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='currentLocation',
            new_name='current_location',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='carModel',
        ),
        migrations.AddField(
            model_name='driver',
            name='car_model',
            field=models.CharField(default='ss', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainuser',
            name='phone',
            field=models.IntegerField(default=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainuser',
            name='prefferd_language',
            field=models.CharField(default='awaa', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_expiry_date',
            field=models.DateField(),
        ),
    ]
