# Generated by Django 5.1.2 on 2025-08-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_currentlocation_rider_current_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
