# Generated by Django 5.1.2 on 2025-08-16 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_reservation_payment_alter_reservation_status_and_more'),
        ('users', '0008_alter_mainuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='past_trips',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_past_rides', to='rides.ride'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='upcoming_trips',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_uncoming_rides', to='rides.ride'),
        ),
    ]
