# Generated by Django 5.1.2 on 2025-08-16 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_reservation_payment_alter_reservation_status_and_more'),
        ('users', '0009_alter_rider_past_trips_alter_rider_upcoming_trips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='past_trips',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past_rides', to='rides.ride'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='upcoming_trips',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uncoming_rides', to='rides.ride'),
        ),
    ]
