# Generated by Django 5.1.2 on 2025-08-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_driver_past_trips_alter_driver_upcoming_trips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='current_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
