# Generated by Django 5.1.2 on 2025-08-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_driver_car_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='prefferd_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
