# Generated by Django 5.1.2 on 2025-08-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_mainuser_prefferd_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainuser',
            old_name='prefferd_language',
            new_name='preferred_language',
        ),
    ]
