# Generated by Django 5.1.2 on 2025-09-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_prefferd_language_mainuser_preferred_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainuser',
            old_name='preferred_language',
            new_name='language1',
        ),
        migrations.AddField(
            model_name='driver',
            name='car_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='car_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='language2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
