# Generated by Django 5.1.2 on 2025-09-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_preferred_language_mainuser_language1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='appadmin',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profiles/default_driver.png', null=True, upload_to='profiles/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='rider',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
