# Generated by Django 5.1.2 on 2025-09-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_mainuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profiles\\cartoon-hand-drawn-blue-car-illustration_2723409.jpg', null=True, upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
