# Generated by Django 6.0.2 on 2026-03-21 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0012_alter_ride_cost_alter_reservation_unique_together'),
        ('users', '0016_alter_driver_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='past_trips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past_rides', to='rides.ride'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='upcoming_trips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uncoming_rides', to='rides.ride'),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
