# Generated by Django 5.2.5 on 2026-04-02 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0012_alter_ride_cost_alter_reservation_unique_together'),
        ('users', '0017_alter_driver_car_number_alter_driver_past_trips_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appadmin',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='mainuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='past_trips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_past_rides', to='rides.ride'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='upcoming_trips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_upcoming_rides', to='rides.ride'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='past_trips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_past_rides', to='rides.ride'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='upcoming_trips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_upcoming_rides', to='rides.ride'),
        ),
    ]
