# Generated by Django 5.2.5 on 2026-05-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_appadmin_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
