# Generated by Django 5.2.5 on 2026-05-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_mainuser_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='location',
        ),
    ]
