# Generated by Django 5.2.5 on 2026-06-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_mainuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
