# Generated by Django 5.2.5 on 2026-06-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_driver_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='past_trips',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='upcoming_trips',
        ),
    ]
