# Generated by Django 5.2.5 on 2026-06-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_rider_past_trips_remove_rider_upcoming_trips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='past_trips',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='upcoming_trips',
        ),
    ]
