# Generated by Django 5.2.5 on 2026-08-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_driver_past_trips_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='language1',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='language2',
        ),
    ]
