# Generated by Django 5.2.5 on 2026-08-07 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_mainuser_language1_remove_mainuser_language2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='license_expiry_date',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_number',
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
