# Generated by Django 5.2.5 on 2026-08-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_passwordresetcode_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
