# Generated by Django 5.2.5 on 2026-08-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_passwordresetcode_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='name',
            field=models.CharField(default='salma', max_length=15),
            preserve_default=False,
        ),
    ]
